name: Deploy Eliminador de imagen

on:
  push:
    branches:
      - main

jobs:
  deploy:
     name: Deploy on local server
     runs-on: self-hosted

     steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Stop existing container
       run: docker compose down || true

     - name: Build and run new container
       run: docker compose up -d --build

     - name: Notify on Discord
       uses: Ilshidur/action-discord@v1.0.0
       with:
         webhook: ${{ secrets.DISCORD_WEBHOOK }}
         message: "🚀 FastAPI desplegado en servidor local tras merge en develop."