name: Deploy Eliminador de imagen

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy on local server
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop existing container
        run: docker compose down || true

      - name: Build and run new container
        run: docker compose up -d --build

      - name: Notify on Discord
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content": "Se realizo un cambio en la aplicación."}' \
               ${{ secrets.DISCORD_WEBHOOK }}

