name: Deploy Eliminador de imagen

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy on local server
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop existing container
        run: docker compose down || true

      - name: Build and run new container
        run: docker compose up -d --build

      - name: Notify on Discord
        uses: tsickert/discord-webhook@v1
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: "🚀 FastAPI desplegado en servidor local tras merge en develop."
